[workspace]
members = [
    "proto-types",
    "proto-messages",
    "gears",
    "trees",
    "database",
    "tendermint",
    "gaia-rs",
    "store",
    "x/bank",
    "x/auth",
]
resolver = "2"

[workspace.dependencies]
ibc-proto = { git = "https://github.com/joneskm/ibc-proto-rs" }
