[package]
edition = "2021"
name = "tx-derive"
version = "0.1.0"

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
darling = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
proc-macro2 = { workspace = true }
